Dim obiektWS : Set obiektWS = CreateObject("WScript.Shell")
Dim nazwaWS(25)
nazwaWS(1) = "%ALLUSERSPROFILE%"
nazwaWS(2) = "%APPDATA%"
nazwaWS(3) = "%COMPUTERNAME%"
nazwaWS(4) = "%CommonProgramFiles%"
nazwaWS(5) = "%CommonProgramFiles(x86)%"
nazwaWS(6) = "%ComSpec%"
nazwaWS(7) = "%HOMEDRIVE%"
nazwaWS(8) = "%HOMEPATH%"
nazwaWS(9) = "%LOCALAPPDATA%"
nazwaWS(10) = "%LOGONSERVER%"
For licznik = 1 To 10
	zmienna = obiektWS.ExpandEnvironmentStrings(nazwaWS(licznik))
	razemWS = razemWS & nazwaWS(licznik) & vbLf & zmienna & vbLf & vbLf
Next : MsgBox razemWS : razemWS = ""
nazwaWS(11) = "%Path%"
nazwaWS(12) = "%PATHEXT%"
nazwaWS(13) = "%ProgramFiles%"
nazwaWS(14) = "%ProgramFiles(X86)%"
nazwaWS(15) = "%SystemDrive%"
nazwaWS(16) = "%SystemRoot%"
nazwaWS(17) = "%TEMP%"
nazwaWS(18) = "%TMP%"
nazwaWS(19) = "%USERDOMAIN%"
nazwaWS(20) = "%USERNAME%"
For licznik = 11 To 20
	zmienna = obiektWS.ExpandEnvironmentStrings(nazwaWS(licznik))
	razemWS = razemWS & nazwaWS(licznik) & vbLf & zmienna & vbLf & vbLf
Next : MsgBox razemWS : razemWS = ""
nazwaWS(21) = "%USERPROFILE%"
nazwaWS(22) = "%WINDIR%"
nazwaWS(23) = "%PUBLIC%"
nazwaWS(24) = "%ProgramData%"
nazwaWS(25) = "%PSModulePath%"
For licznik = 21 To Ubound(nazwaWS)
	zmienna = obiektWS.ExpandEnvironmentStrings(nazwaWS(licznik))
	razemWS = razemWS & nazwaWS(licznik) & vbLf & zmienna & vbLf & vbLf
Next : MsgBox razemWS : razemWS = ""
Set obiektWS = Nothing
